export const FETCH_RECIPES = "FETCH_RECIPES";
export const SET_RECIPES = "SET_RECIPES";
export const SET_RECIPE_DETAILS = "SET_RECIPE_DETAILS";
export const RECIPE_SEARCH_ERROR = "RECIPE_SEARCH_ERROR";
export const SET_SEARCH_TERMS = "SET_SEARCH_TERMS";