export const FETCH_RECIPES = "FETCH_RECIPES";
export const SET_RECIPES = "SET_RECIPES";
export const GET_INDIVIDUAL_RECIPE = "GET_INDIVIDUAL_RECIPE";
export const RECIPE_SEARCH_ERROR = "RECIPE_SEARCH_ERROR";